waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57
  waypoints:
    - id: registed_0_173706000000
      position:
        x: -17.11547
        y: 7.444979
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 0.5
    - id: registed_0_163413000000
      position:
        x: -8.127083
        y: 7.281191
        z: -3
      euler_angles:
        x: 3.141593
        y: 3.141593
        z: -0.091119
      properties:
        - key: goal_radius
          value: 0.5
    - id: registed_0_96504000000
      position:
        x: -8.063078
        y: -6.043276
        z: -3
      euler_angles:
        x: 8.506007e-08
        y: 1.951008e-07
        z: 0.8843422
      properties:
        - key: goal_radius
          value: 0.5
    - id: registed_0_86754000000
      position:
        x: -14.08183
        y: -16.53881
        z: -3
      euler_angles:
        x: 6.817175e-08
        y: 2.1507e-07
        z: 1.012542
      properties:
        - key: goal_radius
          value: 0.5
    - id: registed_0_91705000000
      position:
        x: -17.33611
        y: -4.190577
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.544636
      properties:
        - key: white
          value: false
        - key: stop
          value: ""
        - key: goal_radius
          value: 0.5
    - id: registed_0_91086000000
      position:
        x: -10.13281
        y: -11.01681
        z: -3
      euler_angles:
        x: 7.175247e-08
        y: 2.110054e-07
        z: 1.13289
      properties:
        - key: goal_radius
          value: 0.5
    - id: 3
      position:
        x: -17.06013
        y: 4.220901
        z: -3
      euler_angles:
        x: 1.238722e-07
        y: -1.346523e-07
        z: -1.558395
      properties:
        - key: white
          value: false
        - key: stop
          value: ""
        - key: goal_radius
          value: 0.5
      connections:
        - 1
    - id: registed_0_159234000000
      position:
        x: -5.561128
        y: 4.262179
        z: -3
      euler_angles:
        x: 8.742276e-08
        y: 1.509958e-07
        z: 2.224564
      properties:
        - key: goal_radius
          value: 0.5
    - id: registed_0_103573000000
      position:
        x: -17.56409
        y: -16.81591
        z: -3
      euler_angles:
        x: 1.191055e-07
        y: -1.214063e-07
        z: -0.03079023
      properties:
        - key: stop
          value: ""
        - key: goal_radius
          value: 0.5
        - key: white
          value: false
    - id: registed_0_132722000000
      position:
        x: -5.595613
        y: -3.066028
        z: -3
      euler_angles:
        x: 2.078503e-08
        y: 2.392948e-07
        z: 1.541938
      properties:
        - key: goal_radius
          value: 0.5
    - id: registed_0_95904000000
      position:
        x: -17.46551
        y: -11.55701
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
        - key: goal_radius
          value: 0.5
        - key: white
          value: false
